import type { Metadata } from 'next'
import { Theme, ThemePanel } from '@radix-ui/themes'
import localFont from 'next/font/local'
import '@radix-ui/themes/styles.css'
import '@/styles/globals.css'
import Script from 'next/script'
import 'react-datepicker/dist/react-datepicker.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../public/fonts/Pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_KEY}&autoload=false&libraries=services`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Theme>
          <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
          <Script src={KAKAO_SDK_URL} strategy="beforeInteractive" />
          {children}
          <ThemePanel defaultOpen={false} />
          <div id="portal" />
        </Theme>
      </body>
    </html>
  )
}
