import type { Metadata } from 'next'
import { Theme, ThemePanel } from '@radix-ui/themes'
import localFont from 'next/font/local'
import '@radix-ui/themes/styles.css'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../public/fonts/Pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Theme>
          {children}
          <ThemePanel defaultOpen={false} />
        </Theme>
      </body>
    </html>
  )
}
